In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_12_5_1.xlsx', header = 0)

df_geneData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108005 entries, 0 to 108004
Data columns (total 6 columns):
Variable1    108005 non-null int64
Variable2    108005 non-null int64
Variable3    108005 non-null int64
Variable4    108005 non-null int64
Variable5    108005 non-null int64
Output       108005 non-null int64
dtypes: int64(6)
memory usage: 4.9 MB

In [2]:
df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

,Variable1,Variable2,Variable3,Variable4,Variable5,Output
0,441113131223,323144241343,111423112333,213342114442,211221323122,1
1,234114131413,141213331134,214444424444,111331413113,233441443242,4
2,433443312233,444243434141,124214431113,221441333323,332144422214,3
3,332111133443,423131112334,332313324344,423142243232,311322433331,4
4,331434224334,414221213332,444444221214,322314212213,331434122222,1
5,323321211333,441422121213,442133143122,342234233423,322432444414,4
6,113342443144,432443334324,233232142332,143433141134,223322214123,3
7,241211413323,244244423443,432232244422,114244433333,141422343422,3
8,433112424332,132134323433,142442422323,143132432234,222112114421,1
9,212243314223,422244321334,231132231133,231231144323,434341432122,2
10,112234442342,242314433343,112313113412,242334232242,243311243242,3
11,343112323323,133332114432,223232444224,414411413321,321132321322,3
12,212222323432,232214234322,142321142221,234332322222,322422334232,1
13,223223224323,223341213223,343424322321,223342343344,224232311313,2
14,432232243433,233233444221,323421233223,124224123133,233113112231,3
15,214231422324,332234132214,322332433232,232322332114,123212231323,2
16,112342213342,311332323243,113212122132,412243112232,122442122442,3
17,131124423423,133321134221,122112433222,343223233224,332133433233,1
18,211224211321,433241211222,324344224241,433433334233,224333211312,2
19,212243143214,324341334112,214243243113,113114223112,322113342342,4
20,122432144233,132324423423,233121433421,133222432132,421123221421,1
21,231144211323,244241223242,334331232324,324314231231,414221344244,2
22,322234113313,232422213311,313442442212,122442112322,244242311332,3
23,322132133431,422421221323,122324142231,133111423113,324433113132,3
24,324311142223,244233243333,224312334332,234231322322,331124331112,2
25,234342323142,243143113113,322313213322,113142311243,223212314323,3
26,234424421423,222132321422,344221123432,323112433113,323232431132,3
27,334314232221,242321244214,333423322314,212214231324,314223231342,3
28,243113312243,243322243213,312113243342,132142312112,142213232122,3
29,423223134124,121131421131,424223142434,434221132332,344232344233,4
...,...,...,...,...,...,...
29970,213342112333,231323332323,313311413224,333333214421,422434231133,3
29971,134322214313,214214234212,233232232233,244214233213,211424324321,3
29972,323243112213,232332313122,312142142323,343312314242,122312332313,2
29973,134422321122,433233123223,141423223124,122433122131,123124421423,1
29974,123241232223,433231244233,422434323232,324344221221,333332243232,2
29975,132122243311,132112333232,412143143313,112112412232,412132434232,2
29976,432433133221,322433112423,323432234422,424123224234,233233233424,1
29977,233232233223,312444223231,332323223341,231323322324,311234241233,2
29978,412422113442,242442312213,232343232233,323243223213,323232132213,3
29979,433423322432,324124421123,424123342232,323133332121,133332331433,2
29980,242334332241,221243241221,321324323223,231233323334,334324344233,2
29981,311214314332,442223322332,332214243232,312442342323,343313312343,3
29982,232333421122,432144422423,122122232132,324233321424,421122423321,3
29983,233223232323,213244211231,134232224332,334314211213,234423432213,2
29984,322312213223,223243343243,323213323243,313132332243,242332412232,3
29985,114422223133,234432323232,324122131322,141224323223,122433112432,4
29986,423231332333,441223231231,444224213424,331331333234,233233341243,2
29987,232433243323,232132322431,343222342333,233232324222,232322322434,2
29988,114424334133,333223214322,121233132324,331233331414,324212133244,2
29989,233234442344,432232122333,222324411233,233442233423,131212123313,3
29990,232342322143,343322332231,323112233223,332331424442,312144122133,1
29991,333433321431,331223123131,113122333113,323223132233,323323221423,3
29992,232213324314,331344232324,211332213311,334344234214,233231334211,2
29993,311113243322,133312343343,213213443212,142242322423,142132312311,2
29994,231422141434,423421144232,233343322123,423134223323,121431424423,1
29995,432314223244,214212122311,334214214314,233242333213,234332213232,2
29996,332323243142,412322323323,312113311112,232414423243,223112122232,4
29997,422422432122,132234223323,341422133332,233231321121,423131424122,3
29998,223231314234,323214311131,323224331223,314244232231,132212233321,3
29999,123323311113,142132323312,122313232314,442433243112,322313313323,2

In [3]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5']]
output_y = df_geneDataSelect['Output']

In [4]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [5]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 8, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)

In [6]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
# And call this method for the training data (display only accuracy)
measure_performance(X_test, y_test, clf) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.333

Classification report
             precision    recall  f1-score   support

          1       0.24      0.07      0.11      1222
          2       0.29      0.23      0.26      2446
          3       0.37      0.68      0.48      2583
          4       0.20      0.07      0.10      1249

avg / total       0.29      0.33      0.28      7500


Confusion matrix
[[  87  381  657   97]
 [  91  569 1651  135]
 [ 114  603 1760  106]
 [  71  404  690   84]]

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

measure_performance(X_test, y_test, clf1) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.318

Classification report
             precision    recall  f1-score   support

          1       0.21      0.19      0.20      1222
          2       0.34      0.42      0.38      2446
          3       0.36      0.38      0.37      2583
          4       0.23      0.12      0.16      1249

avg / total       0.31      0.32      0.31      7500


Confusion matrix
[[ 237  416  430  139]
 [ 330 1025  909  182]
 [ 353 1062  970  198]
 [ 233  471  392  153]]

In [ ]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))


measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.328

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1222
          2       0.33      0.99      0.49      2446
          3       0.31      0.02      0.03      2583
          4       0.00      0.00      0.00      1249

avg / total       0.21      0.33      0.17      7500


Confusion matrix
[[   0 1189   33    0]
 [   0 2413   33    0]
 [   0 2538   45    0]
 [   0 1216   33    0]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [ ]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

#To show score clf.score(X_test, y_test) 
measure_performance(X_test, y_test, clf3)