In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('geneData_4_3_1.xlsx', header = 0)

df_geneData.info()

df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
Variable1    1048575 non-null int64
Variable2    1048575 non-null int64
Variable3    1048575 non-null int64
Output       1048575 non-null int64
dtypes: int64(4)
memory usage: 32.0 MB

       Variable1  Variable2  Variable3  Output
0           4411       1313       1223       3
1           2314       4241       3431       1
2           1423       1123       3321       3
3           3421       1444       2211       2
4           2132       3122       1234       1
5           1413       1413       1412       1
6           3331       1342       1444       4
7           4244       4411       1331       4
8           1311       3233       4414       4
9           3242       4433       4433       1
10          2233       4442       4343       4
11          1411       2421       4431       1
12          1322       1441       3333       2
13          3332       1444       2221       4
14          3332       1111       3344       3
15          4231       3111       2334       3
16          3231       3324       3444       2
17          3142       2432       3231       1
18          3224       3333       1433       1
19          4342       2433       4414       2
20          2121       3332       4444       4
21          4221       2143       2231       4
22          2122       1333       1434       1
23          2222       2132       3321       2
24          1133       3441       4221       2
25          1213       4421       3314       3
26          1223       4223       4233       4
27          2332       2432       4444       1
28          4411       3342       4431       4
29          4432       4433       3432       4
...          ...        ...        ...     ...
29970       4411       4424       4444       1
29971       3344       4144       3231       1
29972       4144       4412       4344       4
29973       1441       2241       2323       2
29974       4141       1132       3133       3
29975       1114       1123       1244       2
29976       4311       1244       3323       3
29977       4112       4232       2131       1
29978       1311       1324       3411       4
29979       1332       3344       4424       3
29980       2231       4122       2442       3
29981       3222       2342       1322       3
29982       3313       1133       3213       3
29983       1132       2231       3133       1
29984       2323       1133       2331       3
29985       2243       1433       1113       1
29986       4433       2441       2111       4
29987       4322       4421       2433       2
29988       3343       3342       3131       2
29989       1222       3223       2121       1
29990       4112       1131       2123       1
29991       3412       3222       1432       1
29992       2123       2442       2344       2
29993       3243       2244       2243       2
29994       2432       4432       2432       2
29995       2234       2344       2214       2
29996       3223       2333       4432       3
29997       2234       4422       4314       2
29998       2142       3114       1223       1
29999       3444       2323       2323       2

[30000 rows x 4 columns]

In [9]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3']]
output_y = df_geneDataSelect['Output']

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)

In [10]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 10, min_samples_leaf = 1)
clf = clf.fit(X_train, y_train)

In [11]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        


print('Decision Tree Results:')
measure_performance(X_test, y_test, clf) #Calls measure_performance method

Decision Tree Results:
Accuracy:0.360

Classification report
             precision    recall  f1-score   support

          1       0.24      0.10      0.14      2049
          2       0.37      0.60      0.46      4129
          3       0.38      0.41      0.39      4113
          4       0.25      0.05      0.08      2209

avg / total       0.33      0.36      0.32     12500


Confusion matrix
[[ 210  998  755   86]
 [ 205 2495 1297  132]
 [ 245 2068 1691  109]
 [ 201 1155  743  110]]

In [12]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

print('Random Forest Results:')
measure_performance(X_test, y_test, clf1)

Random Forest Results:
Accuracy:0.334

Classification report
             precision    recall  f1-score   support

          1       0.22      0.22      0.22      2049
          2       0.38      0.43      0.40      4129
          3       0.37      0.39      0.38      4113
          4       0.23      0.14      0.17      2209

avg / total       0.32      0.33      0.33     12500


Confusion matrix
[[ 458  656  706  229]
 [ 588 1788 1391  362]
 [ 590 1504 1624  395]
 [ 428  778  703  300]]

In [13]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)

print('Neural Network Results:')
measure_performance(X_test, y_test, clf2)

Neural Network Results:
Accuracy:0.272

Classification report
             precision    recall  f1-score   support

          1       0.16      0.34      0.22      2049
          2       0.33      0.65      0.44      4129
          3       0.00      0.00      0.00      4113
          4       0.00      0.00      0.00      2209

avg / total       0.14      0.27      0.18     12500


Confusion matrix
[[ 696 1353    0    0]
 [1425 2704    0    0]
 [1436 2677    0    0]
 [ 760 1449    0    0]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [14]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

print('SVM Results:')
measure_performance(X_test, y_test, clf3)

SVM Results:
Accuracy:0.326

Classification report
             precision    recall  f1-score   support

          1       0.14      0.00      0.01      2049
          2       0.28      0.09      0.13      4129
          3       0.33      0.90      0.49      4113
          4       0.00      0.00      0.00      2209

avg / total       0.23      0.33      0.20     12500


Confusion matrix
[[   8  266 1775    0]
 [  19  355 3755    0]
 [  11  387 3715    0]
 [  18  250 1941    0]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)