In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_6_5_1.xlsx', header = 0)

df_geneData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212527 entries, 0 to 212526
Data columns (total 6 columns):
Variable1    212527 non-null int64
Variable2    212527 non-null int64
Variable3    212527 non-null int64
Variable4    212527 non-null int64
Variable5    212527 non-null int64
Output       212527 non-null int64
dtypes: int64(6)
memory usage: 9.7 MB

In [2]:
df_geneDataSelect = df_geneData.head(10000)
df_geneDataSelect

      Variable1  Variable2  Variable3  Variable4  Variable5  Output
0        441113     131223     323144     241343     111423       1
1        123332     133421     144422     112213     231221       2
2        341141     314131     412133     311342     144444       2
3        444411     133141     311323     344144     324244       3
4        344331     223344     424343     414112     421443       1
5        113221     441333     323332     144422     214333       2
6        111133     443423     131112     334332     313324       3
7        444231     422432     323113     224333     314331       4
8        342243     344142     212133     324444     442212       1
9        432231     421221     333143     412222     213233       2
10       121133     344142     212121     344213     314312       2
11       342234     233423     322432     444414     411334       2
12       443144     432443     334324     233232     142332       1
13       434331     411342     233222     141233     241211       4
14       133232     442444     234434     322322     444221       1
15       424443     333314     142234     342234     331124       2
16       433213     213432     343314     244242     232314       3
17       132432     234222     112114     421121     224331       4
18       223422     244321     334231     132231     133231       2
19       311443     234343     414321     222112     234442       3
20       422423     144333     431123     131134     122423       3
21       423224     224331     124324     233431     123233       2
22       313333     211443     222323     244422     441441       1
23       413321     321132     321322     321222     232343       2
24       232214     234322     142321     142221     234332       3
25       222223     224223     342321     223223     224323       2
26       233412     132233     434243     223212     233423       4
27       334422     423231     131324     322322     434332       3
28       323344     422132     342123     322312     422412       3
29       133233     113112     231321     423142     232433       2
...         ...        ...        ...        ...        ...     ...
9970     332214     234231     234322     313221     332241       2
9971     332232     232313     313322     243334     142212       2
9972     133232     433223     333233     433123     224123       2
9973     223232     223324     232233     321422     324314       2
9974     332243     243343     332113     323143     422332       3
9975     234422     423222     143324     122133     221142       3
9976     224314     232124     323231     422333     334314       3
9977     342212     322143     332113     322322     322323       2
9978     331421     222432     321323     423133     112433       1
9979     332324     332332     321334     322322     314332       2
9980     412312     142312     132412     322423     242333       2
9981     432424     331131     222433     133413     133221       4
9982     231132     322412     312311     231424     332323       3
9983     341232     311432     243332     323323     243242       3
9984     121422     423223     322232     323122     433343       3
9985     223224     233232     332211     423231     332342       3
9986     323232     343232     233443     243232     313213       4
9987     334313     442133     132313     223433     421423       2
9988     311213     242121     323333     242213     223323       1
9989     233242     324224     342224     143232     313323       4
9990     243232     233132     222123     122432     422433       3
9991     214332     222331     321224     332231     231232       1
9992     223222     433322     232313     342243     323322       3
9993     324332     233433     433432     332323     232233       3
9994     131422     332312     334332     214233     234323       2
9995     332223     323233     313213     232433     322332       4
9996     331432     234433     433231     421222     332322       4
9997     323422     331132     324343     221323     231122       3
9998     223443     423232     312243     223322     433232       3
9999     222432     322134     432323     232232     431123       2

[10000 rows x 6 columns]

In [3]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5']]
output_y = df_geneDataSelect['Output']

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [4]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 2, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)

In [5]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        


print('Decision Tree Results:')
measure_performance(X_test, y_test, clf) #Calls measure_performance method

Decision Tree Results:
Accuracy:0.321

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00       459
          2       0.33      0.00      0.00       785
          3       0.32      1.00      0.49       802
          4       0.00      0.00      0.00       454

avg / total       0.21      0.32      0.16      2500


Confusion matrix
[[  0   1 458   0]
 [  0   1 784   0]
 [  0   0 802   0]
 [  0   1 453   0]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [6]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

print('Random Forest Results:')
measure_performance(X_test, y_test, clf1)

Random Forest Results:
Accuracy:0.311

Classification report
             precision    recall  f1-score   support

          1       0.20      0.19      0.20      1266
          2       0.34      0.41      0.38      2435
          3       0.35      0.36      0.36      2583
          4       0.20      0.13      0.16      1216

avg / total       0.30      0.31      0.30      7500


Confusion matrix
[[ 246  420  407  193]
 [ 342 1007  892  194]
 [ 362 1078  920  223]
 [ 254  426  380  156]]

In [7]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(150), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))

print('Neural Network Results:')
measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Neural Network Results:
Accuracy:0.323

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1266
          2       0.33      0.98      0.49      2435
          3       0.00      0.00      0.00      2583
          4       0.23      0.04      0.07      1216

avg / total       0.14      0.32      0.17      7500


Confusion matrix
[[   0 1221    0   45]
 [   0 2375    0   60]
 [   0 2522    0   61]
 [   0 1166    0   50]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [8]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

print('SVM Results:')
measure_performance(X_test, y_test, clf3)

SVM Results:
Accuracy:0.345

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1266
          2       0.30      0.13      0.18      2435
          3       0.35      0.88      0.50      2583
          4       0.00      0.00      0.00      1216

avg / total       0.22      0.35      0.23      7500


Confusion matrix
[[   0  235 1031    0]
 [   0  318 2117    0]
 [   0  310 2273    0]
 [   0  200 1016    0]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)