In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_3_10_1.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212527 entries, 0 to 212526
Data columns (total 11 columns):
Variable1     212527 non-null int64
Variable2     212527 non-null int64
Variable3     212527 non-null int64
Variable4     212527 non-null int64
Variable5     212527 non-null int64
Variable6     212527 non-null int64
Variable7     212527 non-null int64
Variable8     212527 non-null int64
Variable9     212527 non-null int64
Variable10    212527 non-null int64
Output        212527 non-null int64
dtypes: int64(11)
memory usage: 17.8 MB

Show header of data imported to dataframe

In [2]:
df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

,Variable1,Variable2,Variable3,Variable4,Variable5,Variable6,Variable7,Variable8,Variable9,Variable10,Output
0,441,113,131,223,323,144,241,343,111,423,1
1,123,332,133,421,144,422,112,213,231,221,2
2,341,141,314,131,412,133,311,342,144,444,2
3,444,411,133,141,311,323,344,144,324,244,3
4,344,331,223,344,424,343,414,112,421,443,1
5,113,221,441,333,323,332,144,422,214,333,2
6,111,133,443,423,131,112,334,332,313,324,3
7,444,231,422,432,323,113,224,333,314,331,4
8,342,243,344,142,212,133,324,444,442,212,1
9,432,231,421,221,333,143,412,222,213,233,2
10,121,133,344,142,212,121,344,213,314,312,2
11,342,234,233,423,322,432,444,414,411,334,2
12,443,144,432,443,334,324,233,232,142,332,1
13,434,331,411,342,233,222,141,233,241,211,4
14,133,232,442,444,234,434,322,322,444,221,1
15,424,443,333,314,142,234,342,234,331,124,2
16,433,213,213,432,343,314,244,242,232,314,3
17,132,432,234,222,112,114,421,121,224,331,4
18,223,422,244,321,334,231,132,231,133,231,2
19,311,443,234,343,414,321,222,112,234,442,3
20,422,423,144,333,431,123,131,134,122,423,3
21,423,224,224,331,124,324,233,431,123,233,2
22,313,333,211,443,222,323,244,422,441,441,1
23,413,321,321,132,321,322,321,222,232,343,2
24,232,214,234,322,142,321,142,221,234,332,3
25,222,223,224,223,342,321,223,223,224,323,2
26,233,412,132,233,434,243,223,212,233,423,4
27,334,422,423,231,131,324,322,322,434,332,3
28,323,344,422,132,342,123,322,312,422,412,3
29,133,233,113,112,231,321,423,142,232,433,2
...,...,...,...,...,...,...,...,...,...,...,...
29970,113,422,122,423,142,122,422,323,223,323,3
29971,244,221,333,224,432,323,224,344,222,131,3
29972,332,314,312,231,333,223,334,243,314,323,2
29973,433,223,342,333,223,223,142,223,333,314,4
29974,232,433,432,223,214,233,334,233,234,431,4
29975,311,214,323,233,212,322,111,323,244,322,3
29976,322,133,322,423,323,224,322,322,133,322,3
29977,334,132,423,223,332,321,224,233,133,224,4
29978,333,314,233,212,221,333,243,214,323,221,3
29979,133,423,223,233,341,423,331,423,423,323,1
29980,221,221,234,231,331,424,221,331,334,233,2
29981,214,344,223,432,341,133,212,212,212,342,2
29982,143,344,332,342,132,332,213,443,221,232,1
29983,223,131,421,222,232,323,123,323,434,133,2
29984,321,213,222,344,344,231,232,233,322,323,2
29985,223,242,312,213,344,422,423,322,133,223,1
29986,133,233,231,132,433,223,233,433,233,432,2
29987,332,322,344,331,331,122,231,332,311,333,2
29988,323,343,133,413,323,323,443,411,331,242,4
29989,223,232,332,234,131,232,232,324,321,432,2
29990,322,344,332,214,333,233,214,344,334,244,3
29991,222,133,213,142,322,223,323,321,232,133,2
29992,324,231,233,431,133,214,232,324,333,221,2
29993,213,342,244,311,232,133,324,322,331,332,2
29994,321,343,133,222,443,122,133,413,243,422,4
29995,433,233,434,133,311,432,234,221,323,332,2
29996,313,334,242,322,123,232,223,323,332,342,3
29997,313,322,432,324,423,322,132,323,423,331,4
29998,432,321,221,221,223,234,421,323,233,433,3
29999,234,322,333,232,142,341,332,342,314,223,2

In [3]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5','Variable6','Variable7','Variable8','Variable9','Variable10']]
output_y = df_geneDataSelect['Output']

Import and use train_test_split, to split data for training
(split data will be used by all algorithms)

In [4]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

Import, fit and use Decision Tree Classifier

In [5]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 3, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)

Create function for the visualisation of metrics, and show results of Decision Tree Classifier

In [6]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
# And call this method for the training data (display only accuracy)
measure_performance(X_test, y_test, clf) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.348

Classification report
             precision    recall  f1-score   support

          1       0.22      0.04      0.06      1266
          2       0.31      0.23      0.26      2435
          3       0.37      0.75      0.50      2583
          4       0.21      0.06      0.09      1216

avg / total       0.30      0.35      0.28      7500


Confusion matrix
[[  47  360  777   82]
 [  55  554 1733   93]
 [  50  509 1941   83]
 [  65  344  739   68]]

Create, fit and show results of Random Forest Tree Classifier

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

measure_performance(X_test, y_test, clf1) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.340

Classification report
             precision    recall  f1-score   support

          1       0.23      0.24      0.23      1266
          2       0.36      0.43      0.39      2435
          3       0.39      0.40      0.40      2583
          4       0.24      0.13      0.17      1216

avg / total       0.33      0.34      0.33      7500


Confusion matrix
[[ 299  426  394  147]
 [ 359 1052  831  193]
 [ 377  989 1039  178]
 [ 245  436  375  160]]

Create, fit and show results of Neural Network Multi-Layer Perceptron Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))


measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.321

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1266
          2       0.27      0.05      0.09      2435
          3       0.35      0.82      0.49      2583
          4       0.17      0.12      0.14      1216

avg / total       0.23      0.32      0.22      7500


Confusion matrix
[[   0  115  996  155]
 [   0  132 2036  267]
 [   0  156 2128  299]
 [   0   85  986  145]]

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Imports, fits and tests the Support Vector Machine classifier

In [ ]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

#To show score clf.score(X_test, y_test) 
measure_performance(X_test, y_test, clf3)